apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
        tier: db 
        project: expense # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: srikanthhg/mysql:expense

        # env:
        # - name: MYSQL_ROOT_PASSWORD # This is the name of the environment variable in linux machine
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql  # This is the name of the secret
        #       key: MYSQL_ROOT_PASSWORD   # This is the key in the secret   ---working good

        # envFrom:
        #   - secretRef:
        #       name: mysql       #name of the secret   ---working good

        volumeMounts:
        - name: mysql-secret-volume
          mountPath: "/etc/mysql-secret"
          readOnly: true
      volumes:
      - name: mysql-secret-volume
        secret:
          secretName: mysql # Provide the name of the secret you want to mount.
  


  # volumeClaimTemplates:
  # - metadata:
  #     name: mysql-data



  #     volumeClaimTemplates:
  #   - metadata:
  #       name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
  #     spec:
  #       accessModes:
  #       - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 5Gi
  #       storageClassName: standard

      